name: Build Vue
on: 
  push:
    tags:
      - '*'
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue App
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Variables
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Build Archive
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release.zip'
          directory: './dist'
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: HUI-Builder ${{ steps.vars.outputs.tag }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create Version File
        run: echo "${{ steps.vars.outputs.tag }}" > VERSION.txt
      - name: Upload Release Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/release.zip
          asset_name: builder_static.zip
          asset_content_type: application/zip
      - name: Upload Version File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./VERSION.txt
          asset_name: VERSION
          asset_content_type: text/plain